path_classifiers:
  library:
  - 3rdparty/*
  test:
  - exclude: tests/quotest.cpp # Let alerts from this come up too
extraction:
  cpp:
    prepare:
      packages: # Assuming package base of eoan
      - qtmultimedia5-dev
#    after_prepare:
#    - git clone https://gitlab.matrix.org/matrix-org/olm.git
#    - pushd olm
#    - cmake . -Bbuild -GNinja
#    - cmake --build build
#    - popd
    configure:
      command: "CXX=clang++-9 cmake . -GNinja" # -DOlm_DIR=olm/build"
